site_name: Structures
repo_name: Nezuo/structures
repo_url: https://github.com/Nezuo/structures

nav:
  - What is Structures?: index.md
  - Structures:
    - Map: map.md
    - Queue: queue.md
    - Set: set.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: amber
    accent: orange

markdown_extensions:
  - codehilite:
      linenums: true
  - toc:
      permalink: true