site_name: Structures
repo_name: Nezuo/structures
repo_url: https://github.com/Nezuo/structures

nav:
  - What is Structures?: index.md
  - Structures:
    - DoublyLinkedList: doublylinkedlist.md
    - LinkedList: linkedlist.md
    - List: list.md
    - Map: map.md
    - OrderedMap: orderedmap.md
    - OrderedSet: orderedset.md
    - Queue: queue.md
    - Set: set.md
    - Stack: stack.md
  - Classes:
    - DoublyLinkedListNode: doublylinkedlistnode.md
    - LinkedListNode: linkedlistnode.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: amber
    accent: orange

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - toc:
      permalink: true