name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate roblox.toml
        run: selene generate-roblox-std

      - name: Run Selene
        run: selene src
  unit-test:
    name: unit-test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Roblox
        uses: OrbitalOwen/roblox-win-installer-action@1.0
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 5
      
      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build place
        run: rojo build -o structures.rbxlx

      - name: Run tests
        run: run-in-roblox --place structures.rbxlx --script test/runTests.server.lua
        timeout-minutes: 5
