name: Deploy Documentation
 
on:
  push:
    branches:
     - master

jobs:
  build:
    name: Build and deploy documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy documentation
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
