name: Unit Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  unit-tests:
    name: unit-tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Roblox
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ secrets.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 5

      - uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build place
        run: rojo build -o structures.rbxlx

      - name: Run tests
        run: run-in-roblox --place structures.rbxlx --script test/runTests.server.lua
        timeout-minutes: 5
